plugins = bundled,kong-plugin-rbac,kong-plugin-go-wait,kong-plugin-go-log

pluginserver_names = kong-plugin-rbac,kong-plugin-go-wait,kong-plugin-go-log

go_plugins_dir = /go-plugins

pluginserver_kong_plugin_rbac_socket = /usr/local/kong/kong-plugin-rbac.socket
pluginserver_kong_plugin_rbac_start_cmd = /go-plugins/kong-plugin-rbac
pluginserver_kong_plugin_rbac_query_cmd = /go-plugins/kong-plugin-rbac -dump

pluginserver_kong_plugin_go_wait_socket = /usr/local/kong/kong-plugin-go-wait.socket
pluginserver_kong_plugin_go_wait_start_cmd = /go-plugins/kong-plugin-go-wait
pluginserver_kong_plugin_go_wait_query_cmd = /go-plugins/kong-plugin-go-wait -dump

pluginserver_kong_plugin_go_log_socket = /usr/local/kong/kong-plugin-go-log.socket
pluginserver_kong_plugin_go_log_start_cmd = /go-plugins/kong-plugin-go-log
pluginserver_kong_plugin_go_log_query_cmd = /go-plugins/kong-plugin-go-log -dump
