apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: kong
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: https
      port: 443
      targetPort: 8443
    - name: api
      port: 8001
      targetPort: 8001
    - name: ui
      port: 8002
      targetPort: 8002

  selector:
    app: kong
