apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: kong
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
    - name: https
      port: 443
      targetPort: 8443
  selector:
    app: kong
